### ISSUE TITLE
$this->aauth->control function

### ISSUE THREAD

**Issue by manukieli** [magefly/CodeIgniter-Aauth#236]
I've a user that have the permision "admin_dashboard", but is group not.
When I use this function to check if the user have the permision or not<br>`$this->aauth->control('admin_dashboard')`<br>The return false.<br>It's not correct, because the user have it, but the group not.<br>I've change the line 424<br>`}else if ( ! $this->is_allowed($perm_id) OR ! $this->is_group_allowed($perm_id) ){`<br>to<br>`}else if ( ! $this->is_allowed($perm_id) AND ! $this->is_group_allowed($perm_id) ){`<br>And now work well.
I don't know if this change can affect the rest of the execution of the script.

**Comment by joaocustodio** [comment]
Yes, this is wrong, and it is not necessary to call is_group_allowed because is_allowed already checks whether the user has the permission, or if it participates if any group that has it. You can leave it like this: `} else if ( ! $this->is_allowed ($perm_id) ) {`
which will reduce the number of queries in your database.

**Comment by REJack** [comment]
Oh yeah you are right, feel free to create a PR for this.

**Comment by REJack** [comment]
Issue closed, PR merged in master repo
